# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    amadeus_key: ZRjgUbT6jlJZlEvY86DrhyOrXAGzvANA
services:

    hotel.search_filter:
        parent:    "api_platform.doctrine.orm.search_filter"
        arguments: [ { name: "partial", address: "exact", geo.latitude: "partial", geo.longitude: "partial"  } ]
        tags:      [ { name: 'api_platform.filter', id: 'hotel.search' } ]


    hotel.collection_data_provider:
        class: 'AppBundle\DataProvider\HotelCollectionDataProvider'
        arguments: ["@request_stack","@doctrine", "%amadeus_key%"]
        tags:
            -  { name: 'api_platform.collection_data_provider', priority: 2 }